language: erlang
script: "make"
after_script:
  - "test/test.sh"
otp_release:
  - R16B03-1
notifications:
  email:
    - d.klionsky@dev.powermemobile.com
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
